//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quiz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_QUESTIONS
    {
        public int QUESTION_ID { get; set; }
        [Display(Name = "Question")]
        [Required(ErrorMessage = "field must be filled*")]
        public string Q_TEXT { get; set; }

        [Display(Name = "Option-A")]
        [Required(ErrorMessage = "field must be filled*")]
        public string OPA { get; set; }

        [Display(Name = "Option-B")]
        [Required(ErrorMessage = "field must be filled*")]
        public string OPB { get; set; }

        [Display(Name = "Option-C")]
        [Required(ErrorMessage = "field must be filled*")]
        public string OPC { get; set; }

        [Display(Name = "Option-D")]
        [Required(ErrorMessage = "field must be filled*")]
        public string OPD { get; set; }

        [Display(Name = "Correct Option")]
        [Required(ErrorMessage = "field must be filled*")]
        public string COP { get; set; }

        [Display(Name = "Subject")]
        public Nullable<int> Q_FK_CATID { get; set; }
    
        public virtual TBL_CATEGORY TBL_CATEGORY { get; set; }
    }
}
