//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quiz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_STUDENT()
        {
            this.TBL_SETEXAM = new HashSet<TBL_SETEXAM>();
        }
    
        public int S_ID { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "field must be filled*")]
        public string S_NAME { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "field must be filled*")]
        public string S_PASSWORD { get; set; }
        public string S_IMAGE_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SETEXAM> TBL_SETEXAM { get; set; }
    }
}
